apiVersion: v1
kind: Secret
metadata:
  name: drupal-mysql-secret
type: Opaque
data:
  # MYSQL_ROOT_PASSWORD: root_password
  # MYSQL_DATABASE: drupal-database
  # MYSQL_USER: root
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA==
  MYSQL_DATABASE: ZHJ1cGFsLWRhdGFiYXNl
  MYSQL_USER: cm9vdA==
