apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-nfs-pv-claim
  namespace: rook-nfs
spec:
  storageClassName: "rook-nfs-share1"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
