apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-lb
  name: nginx-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-lb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-lb
    spec:
      containers:
      - image: nginx
        name: nginx-lb
        ports:
        - containerPort: 80
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-lb
  type: LoadBalancer
