apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-np
  name: nginx-np
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-np
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-np
    spec:
      containers:
      - image: nginx
        name: nginx-np
        ports:
        - containerPort: 80
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-np
  type: NodePort
